//! `rbs setup`: provision a host. See `docs/features/setup.md`.

use std::collections::BTreeMap;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

use rbs_config::Config;
use thiserror::Error;
use tracing::{info, warn};

use crate::paths::Paths;
use crate::runner::{Runner, RunnerError};
use crate::{Role, SetupOpts};

/// Exact kache remote config for the shared MinIO store (kache silently
/// ignores malformed TOML, so the shape matters and `kache stats` verifies it).
pub const KACHE_CONFIG_DEFAULT: &str = "[cache.remote]\ntype = \"s3\"\nbucket = \"kache\"\nendpoint = \"http://127.0.0.1:9100\"\nregion = \"us-east-1\"\nprofile = \"rbs\"\nprefix = \"artifacts\"\n";
pub const DEFAULT_ENDPOINT: &str = "http://127.0.0.1:9100";
pub const DEFAULT_BUCKET: &str = "kache";
pub const AWS_PROFILE: &str = "rbs";
const UNIT_TEMPLATE: &str = include_str!("../../../deploy/systemd/rbs-server.service");
const UNIT_NAME: &str = "rbs-server";
const GC_SERVICE_TEMPLATE: &str = include_str!("../../../deploy/systemd/rbs-store-gc.service");
/// Timer unit text (no substitutions needed).
pub const STORE_GC_TIMER: &str = include_str!("../../../deploy/systemd/rbs-store-gc.timer");
const GC_UNIT_NAME: &str = "rbs-store-gc";

#[derive(Debug, Error)]
pub enum SetupError {
    #[error("failed to read {path}: {source}")]
    Read {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to write {path}: {source}")]
    Write {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error(
        "missing {path}; create it with lines KACHE_S3_ACCESS_KEY=… and KACHE_S3_SECRET_KEY=… (see deploy/minio.md)"
    )]
    MissingMinioEnv { path: PathBuf },
    #[error("{path} does not define {key}")]
    MissingMinioKey { path: PathBuf, key: &'static str },
    #[error(
        "kache remote is not configured: `kache stats` did not print `Remote:     s3://…`; check {config}\n--- kache stats ---\n{stdout}"
    )]
    KacheRemoteNotConfigured { config: PathBuf, stdout: String },
    #[error("`{program} {args}` failed: {detail}")]
    CommandFailed {
        program: String,
        args: String,
        detail: String,
    },
    #[error("could not link shim {shim} to {target}: {source}")]
    Shim {
        shim: PathBuf,
        target: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error(transparent)]
    Runner(#[from] RunnerError),
}

/// Generate the role-specific `~/.config/rbs/config.toml` text.
pub fn generate_config(role: Role) -> String {
    let mut cfg = Config::default();
    cfg.server.reserve_cores = 4;
    match role {
        Role::Client => {
            cfg.server.max_jobs = 3;
            cfg.server.job_mem_max_gib = 12;
            cfg.server.min_mem_available_gib = 8;
        }
        Role::Server => {
            cfg.server.max_jobs = 12;
            cfg.server.job_mem_max_gib = 24;
            cfg.server.min_mem_available_gib = 16;
            cfg.remote.enabled = false;
        }
    }
    let body = toml::to_string_pretty(&cfg).unwrap_or_else(|e| {
        // Config is plain data; serialization cannot fail short of a bug.
        warn!(error = %e, "config serialization failed; falling back to defaults");
        String::new()
    });
    format!(
        "# Generated by `rbs setup --role {}`. Edit freely; rerun with --force to regenerate.\n{body}",
        role.name()
    )
}

/// kache config with overridable endpoint/bucket.
pub fn kache_config(endpoint: &str, bucket: &str) -> String {
    format!(
        "[cache.remote]\ntype = \"s3\"\nbucket = \"{bucket}\"\nendpoint = \"{endpoint}\"\nregion = \"us-east-1\"\nprofile = \"{AWS_PROFILE}\"\nprefix = \"artifacts\"\n"
    )
}

/// Render the systemd user unit for this binary.
pub fn render_unit(self_exe: &Path) -> String {
    UNIT_TEMPLATE.replace("{self_exe}", &self_exe.display().to_string())
}

/// Render the store-gc oneshot service for this binary.
pub fn render_store_gc_service(self_exe: &Path) -> String {
    GC_SERVICE_TEMPLATE.replace("{self_exe}", &self_exe.display().to_string())
}

/// Minimal line diff (LCS), `-`/`+`/` ` prefixed, one line per entry.
pub fn line_diff(old: &str, new: &str) -> String {
    let a: Vec<&str> = old.lines().collect();
    let b: Vec<&str> = new.lines().collect();
    let (n, m) = (a.len(), b.len());
    let mut lcs = vec![vec![0usize; m + 1]; n + 1];
    for i in (0..n).rev() {
        for j in (0..m).rev() {
            lcs[i][j] = if a[i] == b[j] {
                lcs[i + 1][j + 1] + 1
            } else {
                lcs[i + 1][j].max(lcs[i][j + 1])
            };
        }
    }
    let mut out = String::new();
    let (mut i, mut j) = (0, 0);
    while i < n && j < m {
        if a[i] == b[j] {
            out.push_str(&format!(" {}\n", a[i]));
            i += 1;
            j += 1;
        } else if lcs[i + 1][j] >= lcs[i][j + 1] {
            out.push_str(&format!("-{}\n", a[i]));
            i += 1;
        } else {
            out.push_str(&format!("+{}\n", b[j]));
            j += 1;
        }
    }
    for l in &a[i..] {
        out.push_str(&format!("-{l}\n"));
    }
    for l in &b[j..] {
        out.push_str(&format!("+{l}\n"));
    }
    out
}

/// Return `existing` with the `[profile]` section set to the given keys,
/// appending it when absent and leaving every other section byte-for-byte.
pub fn aws_credentials_with_profile(
    existing: &str,
    profile: &str,
    access_key: &str,
    secret_key: &str,
) -> String {
    let header = format!("[{profile}]");
    let section = format!(
        "{header}\naws_access_key_id = {access_key}\naws_secret_access_key = {secret_key}\n"
    );
    let lines: Vec<&str> = existing.lines().collect();
    let Some(start) = lines.iter().position(|l| l.trim() == header) else {
        let mut out = existing.to_string();
        if !out.is_empty() && !out.ends_with('\n') {
            out.push('\n');
        }
        if !out.is_empty() {
            out.push('\n');
        }
        out.push_str(&section);
        return out;
    };
    let end = lines[start + 1..]
        .iter()
        .position(|l| l.trim_start().starts_with('['))
        .map(|p| start + 1 + p)
        .unwrap_or(lines.len());
    let mut out = String::new();
    for l in &lines[..start] {
        out.push_str(l);
        out.push('\n');
    }
    out.push_str(&section);
    for l in &lines[end..] {
        out.push_str(l);
        out.push('\n');
    }
    out
}

/// Parse a `KEY=VALUE` env file (`export` prefix, quotes and `#` comments tolerated).
fn parse_env_file(text: &str) -> BTreeMap<String, String> {
    text.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .filter_map(|l| {
            let l = l.strip_prefix("export ").unwrap_or(l);
            let (k, v) = l.split_once('=')?;
            let v = v.trim().trim_matches('"').trim_matches('\'');
            Some((k.trim().to_string(), v.to_string()))
        })
        .collect()
}

fn read_opt(path: &Path) -> Result<Option<String>, SetupError> {
    match std::fs::read_to_string(path) {
        Ok(s) => Ok(Some(s)),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(source) => Err(SetupError::Read {
            path: path.to_path_buf(),
            source,
        }),
    }
}

fn write_file(path: &Path, text: &str, mode: Option<u32>) -> Result<(), SetupError> {
    let wrap = |source| SetupError::Write {
        path: path.to_path_buf(),
        source,
    };
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(wrap)?;
    }
    std::fs::write(path, text).map_err(wrap)?;
    if let Some(m) = mode {
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(m)).map_err(wrap)?;
    }
    Ok(())
}

/// Write a user-owned config file: create if absent, diff-and-skip if it
/// differs (unless `force`). Returns whether the file now holds `text`.
fn write_config_file(path: &Path, text: &str, force: bool) -> Result<bool, SetupError> {
    match read_opt(path)? {
        None => {
            write_file(path, text, None)?;
            info!(path = %path.display(), "wrote config");
            Ok(true)
        }
        Some(existing) if existing == text => {
            info!(path = %path.display(), "config up to date");
            Ok(true)
        }
        Some(existing) if force => {
            write_file(path, text, None)?;
            warn!(path = %path.display(), "overwrote existing config (--force)");
            let _ = existing;
            Ok(true)
        }
        Some(existing) => {
            warn!(path = %path.display(), "exists and differs from generated; keeping yours (rerun with --force to overwrite)");
            println!("--- {} (existing)\n+++ generated", path.display());
            print!("{}", line_diff(&existing, text));
            Ok(false)
        }
    }
}

fn run_checked(runner: &dyn Runner, program: &str, args: &[&str]) -> Result<String, SetupError> {
    let out = runner.run(program, args)?;
    if out.success() {
        Ok(out.stdout)
    } else {
        Err(SetupError::CommandFailed {
            program: program.to_string(),
            args: args.join(" "),
            detail: out.failure_detail(),
        })
    }
}

pub fn kache_stats_has_remote(stdout: &str) -> bool {
    stdout.lines().any(|l| l.starts_with("Remote:     s3://"))
}

/// Step 2: kache config, AWS profile, validation via `kache stats`.
fn setup_kache(runner: &dyn Runner, paths: &Paths, force: bool) -> Result<(), SetupError> {
    let env_path = paths.minio_env();
    let env = parse_env_file(&read_opt(&env_path)?.ok_or(SetupError::MissingMinioEnv {
        path: env_path.clone(),
    })?);
    let key = |k: &'static str| {
        env.get(k)
            .filter(|v| !v.is_empty())
            .cloned()
            .ok_or(SetupError::MissingMinioKey {
                path: env_path.clone(),
                key: k,
            })
    };
    let access = key("KACHE_S3_ACCESS_KEY")?;
    let secret = key("KACHE_S3_SECRET_KEY")?;
    let endpoint = env
        .get("KACHE_S3_ENDPOINT")
        .cloned()
        .unwrap_or_else(|| DEFAULT_ENDPOINT.to_string());
    let bucket = env
        .get("KACHE_S3_BUCKET")
        .cloned()
        .unwrap_or_else(|| DEFAULT_BUCKET.to_string());

    let kache_cfg = paths.kache_config();
    write_config_file(&kache_cfg, &kache_config(&endpoint, &bucket), force)?;

    let creds = paths.aws_credentials();
    let existing = read_opt(&creds)?.unwrap_or_default();
    let updated = aws_credentials_with_profile(&existing, AWS_PROFILE, &access, &secret);
    if let Some(dir) = creds.parent() {
        std::fs::create_dir_all(dir).map_err(|source| SetupError::Write {
            path: dir.to_path_buf(),
            source,
        })?;
        let _ = std::fs::set_permissions(dir, std::fs::Permissions::from_mode(0o700));
    }
    if updated != existing {
        info!(path = %creds.display(), profile = AWS_PROFILE, "updated aws profile");
    }
    write_file(&creds, &updated, Some(0o600))?;

    let kache = paths.kache_bin();
    let stats = run_checked(runner, &kache, &["stats"])?;
    if !kache_stats_has_remote(&stats) {
        return Err(SetupError::KacheRemoteNotConfigured {
            config: kache_cfg,
            stdout: stats,
        });
    }
    info!(endpoint, bucket, "kache remote verified");
    Ok(())
}

/// Step 3: systemd user units + kache daemon. The store-gc timer runs only on
/// the server: that host sees every remote build, so its kache index is the
/// global usage view, and one GC per store avoids racing evictors.
fn setup_services(runner: &dyn Runner, paths: &Paths, role: Role) -> Result<(), SetupError> {
    let unit = paths
        .systemd_user_dir()
        .join(format!("{UNIT_NAME}.service"));
    write_file(&unit, &render_unit(&paths.self_exe), None)?;
    info!(path = %unit.display(), "installed systemd user unit");
    if role == Role::Server {
        let gc_service = paths
            .systemd_user_dir()
            .join(format!("{GC_UNIT_NAME}.service"));
        write_file(&gc_service, &render_store_gc_service(&paths.self_exe), None)?;
        let gc_timer = paths
            .systemd_user_dir()
            .join(format!("{GC_UNIT_NAME}.timer"));
        write_file(&gc_timer, STORE_GC_TIMER, None)?;
        info!(service = %gc_service.display(), timer = %gc_timer.display(), "installed store-gc units");
    }
    run_checked(runner, "systemctl", &["--user", "daemon-reload"])?;
    run_checked(
        runner,
        "systemctl",
        &["--user", "enable", "--now", UNIT_NAME],
    )?;
    info!(unit = UNIT_NAME, "enabled and started");
    if role == Role::Server {
        let timer = format!("{GC_UNIT_NAME}.timer");
        run_checked(runner, "systemctl", &["--user", "enable", "--now", &timer])?;
        info!(unit = timer, "enabled and started");
    }

    let kache = paths.kache_bin();
    let out = runner.run(&kache, &["daemon", "install"])?;
    if out.success() {
        info!("kache daemon installed");
    } else if out.failure_detail().to_lowercase().contains("already") {
        info!("kache daemon already installed");
    } else {
        return Err(SetupError::CommandFailed {
            program: kache,
            args: "daemon install".into(),
            detail: out.failure_detail(),
        });
    }
    Ok(())
}

/// Step 4: the `cargo` shim.
fn setup_shim(paths: &Paths) -> Result<(), SetupError> {
    let dir = paths.shim_dir();
    std::fs::create_dir_all(&dir).map_err(|source| SetupError::Write {
        path: dir.clone(),
        source,
    })?;
    let shim = dir.join("cargo");
    let wrap = |source| SetupError::Shim {
        shim: shim.clone(),
        target: paths.self_exe.clone(),
        source,
    };
    match std::fs::remove_file(&shim) {
        Ok(()) => {}
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => return Err(wrap(e)),
    }
    match std::fs::hard_link(&paths.self_exe, &shim) {
        Ok(()) => info!(shim = %shim.display(), kind = "hardlink", "shim linked"),
        Err(e) => {
            warn!(error = %e, "hardlink failed; falling back to symlink");
            std::os::unix::fs::symlink(&paths.self_exe, &shim).map_err(wrap)?;
            info!(shim = %shim.display(), kind = "symlink", "shim linked");
        }
    }
    println!("Add the shim to PATH for agent environments:");
    println!("  export PATH=\"$HOME/.local/share/rbs/shim:$PATH\"");
    Ok(())
}

/// Step 5: provision the remote host.
fn setup_remote(
    runner: &dyn Runner,
    paths: &Paths,
    host: &str,
    force: bool,
) -> Result<(), SetupError> {
    let exe = paths.self_exe.display().to_string();
    info!(host, "copying rbs binary");
    run_checked(runner, "ssh", &[host, "mkdir", "-p", ".local/bin"])?;
    run_checked(runner, "scp", &[&exe, &format!("{host}:.local/bin/rbs")])?;
    let mut args = vec![host, ".local/bin/rbs", "setup", "--role", "server"];
    if force {
        args.push("--force");
    }
    info!(host, "running remote setup");
    let out = run_checked(runner, "ssh", &args)?;
    if !out.trim().is_empty() {
        println!("--- {host}: rbs setup ---");
        print!("{out}");
    }
    Ok(())
}

/// Testable core of [`crate::setup`].
pub fn setup_with(runner: &dyn Runner, paths: &Paths, opts: &SetupOpts) -> Result<(), SetupError> {
    let paths = Paths {
        self_exe: opts.self_exe.clone(),
        ..paths.clone()
    };
    info!(role = opts.role.name(), home = %paths.home.display(), "rbs setup");
    write_config_file(&paths.rbs_config(), &generate_config(opts.role), opts.force)?;
    setup_kache(runner, &paths, opts.force)?;
    setup_services(runner, &paths, opts.role)?;
    setup_shim(&paths)?;
    if let (Role::Client, Some(host)) = (opts.role, opts.remote_host.as_deref()) {
        setup_remote(runner, &paths, host, opts.force)?;
    } else if opts.remote_host.is_some() {
        warn!("--remote-host ignored for role server");
    }
    info!("setup complete; run `rbs doctor --remote` to verify");
    Ok(())
}
